services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      # Container runtime override (compose) for DB path on volume
      DATABASE_URL: ${DATABASE_URL:-sqlite:////data/app.sqlite}
    volumes:
      - sqlite_data:/data
      - prompt_templates:/app/prompt-templates
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 10s

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 10s

volumes:
  sqlite_data:
  prompt_templates:
