version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r backend/requirements.txt && uvicorn backend.app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ../../:/app:rw
    env_file:
      - ../../.env.local-hf
    ports:
      - "8000:8000"
    environment:
      - CORS_ALLOWED_ORIGINS=*
    restart: unless-stopped
