name: pack.global.v1
match: {}
directives:
  sections:
    constraints:
      - Be clear and precise
      - Avoid harmful content
  max_tokens: 4096
  temperature: 0.3
  examples_count: 1
  json_mode: false
operators:
  baseline:
    - apply_role_hdr
    - apply_constraints
    - apply_io_format
    - apply_examples
    - apply_quality_bar
